apiVersion: v1
kind: Service
metadata:
  name: {{ template "ozwdaemon.fullname" . }}
  labels:
    {{ include "ozwdaemon.labels" . | indent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{ tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
spec:
  publishNotReadyAddresses: true
  {{ if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP | quote  }}
  {{ end }}
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type "LoadBalancer" -}} {{ if .Values.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end -}}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.service.loadBalancerSourceRanges | nindent 2}}
  {{ end -}}
  {{- end -}}
  ports:
    - port: {{ .Values.service.port.admin }}
      targetPort: ozw-admin
      protocol: TCP
      name: ozw-admin
    - port: {{ .Values.service.port.vnc }}
      targetPort: ozw-vnc
      protocol: TCP
      name: ozw-vnc
    - port: {{ .Values.service.port.http }}
      targetPort: ozw-http
      protocol: TCP
      name: ozw-http
  selector:
    {{- include "ozwdaemon.selectorLabels" . | nindent 6 }}